name: npm test
on: 
  workflow_dispatch:

env:
  NODE_VERSION=14
         
jobs:
  job1:
    runs-on: ubuntu-latest
    name : job1
    steps:
    - name: test 
      uses: actions/checkout@v3
    - name: test 2
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
    - name: install npm    
      run: |
          npm install
          node -v
          echo 'Env var $NODE_VERSION'
  job2:
    runs-on: ubuntu-latest
    name : job2
    steps:
    - name: test 
      uses: actions/checkout@v3
    - name: test 2
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: install npm    
      run: |
          npm install
    - name: test npm    
      run: |
          npm test
   
   