name: interact with Github API
on: 
  pull_request:

env: 
  MY_TOKEN: ${{ secrets.MY_TOKEN }}

jobs:
  create-issue:
    permissions:
      issues: write
    outputs:
      output1: ${{ steps.short_sha.outputs.short_sha }}
    runs-on: ubuntu-latest
    steps:
    - id: short_sha
      run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
    - name: interact with GH
      run: |
       curl --request POST \
       --url https://api.github.com/repos/${}/issues \
       --header 'authorization: Bearer ${{env.MY_TOKEN}}' \
       --header 'content-type: application/json' \
       --data '{
          "title": "Automated issue for commit: ${{ steps.short_sha.outputs.sha_short }}",
          "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ steps.short_sha.outputs.sha_short }}_."
          }' \
       --fail